Docker registry url changes
With reference to below error, proposing the change to update the URL 

```#  helm repo add docker-registry https://kubernetes-charts.storage.googleapis.com/
Error: repo "https://kubernetes-charts.storage.googleapis.com/" is no longer available; try "https://charts.helm.sh/stable" instead
```